"""update

Revision ID: a36f364eba53
Revises: None
Create Date: 2016-03-09 16:08:09.121000

"""

# revision identifiers, used by Alembic.
revision = 'a36f364eba53'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_done')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_done', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
